// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace CalculadoraProject
{
	public partial class ControladorVentana : NSWindowController
	{
		public ControladorVentana (IntPtr handle) : base (handle)
		{
		}

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();

            // Remover titulo de la ventana
            base.Window.Title = "";
            // Hacer transparente la barra de titulo de la ventana
            base.Window.TitlebarAppearsTransparent = true;

            // Define color de fondo de la ventana a 5A5C5C
            base.Window.BackgroundColor = NSColor.FromRgb(88 / 255f, 86 / 255f, 86 / 255f);
        }
    }
}
